export const interestList = [
  { id: 0, label: "Hunting Cafe" },
  { id: 1, label: "Drama Series" },
  { id: 2, label: "Food" },
  { id: 3, label: "Documenter" },
  { id: 4, label: "Fantasy Movie" },
  { id: 5, label: "Trip" },
  { id: 6, label: "Animation" },
  { id: 7, label: "Criminal Series" },
  { id: 8, label: "K-Pop" },
  { id: 9, label: "Soul Music" },
  { id: 10, label: "Punk Rock" },
  { id: 11, label: "Art" },
  { id: 12, label: "Music Theater" },
  { id: 13, label: "Pop Music" },
  { id: 14, label: "Sport" },
  { id: 15, label: "Emo Music" },
  { id: 16, label: "Explore" },
  { id: 17, label: "Photography" },
  { id: 18, label: "Reading" },
];
